package com.networknt.oauth.user.handler;

import com.networknt.client.Client;
import com.networknt.config.Config;
import com.networknt.exception.ApiException;
import com.networknt.exception.ClientException;
import com.networknt.status.Status;
import org.apache.commons.io.IOUtils;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.junit.Assert;
import org.junit.ClassRule;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.UnsupportedEncodingException;

/**
* Generated by swagger-codegen
*/
public class Oauth2UserPostHandlerTest {
    @ClassRule
    public static TestServer server = TestServer.getInstance();

    static final Logger logger = LoggerFactory.getLogger(Oauth2UserPostHandlerTest.class);

    @Test
    public void testOauth2UserPostHandler() throws ClientException, ApiException, UnsupportedEncodingException {
        String user = "{\"userId\":\"stevehu\",\"userType\":\"employee\",\"firstName\":\"Steve\",\"lastName\":\"Hu\",\"email\":\"stevehu@gmail.com\",\"password\":\"123456\",\"passwordConfirm\":\"123456\"}";
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:6885/oauth2/user");
        httpPost.setHeader("Content-type", "application/json");
        httpPost.setEntity(new StringEntity(user));
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            //logger.debug("StatusCode = " + response.getStatusLine().getStatusCode());
            Assert.assertEquals(200, response.getStatusLine().getStatusCode());
            String body = IOUtils.toString(response.getEntity().getContent(), "utf8");
            logger.debug("Response body = " + body);
            Assert.assertNotNull(body);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Test
    public void testUserIdExists() throws ClientException, ApiException, UnsupportedEncodingException {
        String user = "{\"userId\":\"admin\",\"userType\":\"employee\",\"firstName\":\"Steve\",\"lastName\":\"Hu\",\"email\":\"admin@gmail.com\",\"password\":\"123456\",\"passwordConfirm\":\"123456\"}";
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:6885/oauth2/user");
        httpPost.setHeader("Content-type", "application/json");
        httpPost.setEntity(new StringEntity(user));
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            int statusCode = response.getStatusLine().getStatusCode();
            String body = IOUtils.toString(response.getEntity().getContent(), "utf8");
            Assert.assertEquals(400, statusCode);
            if(statusCode == 400) {
                Status status = Config.getInstance().getMapper().readValue(body, Status.class);
                Assert.assertNotNull(status);
                Assert.assertEquals("ERR12020", status.getCode());
                Assert.assertEquals("USER_ID_EXISTS", status.getMessage()); // response_type missing
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Test
    public void testEmailExists() throws ClientException, ApiException, UnsupportedEncodingException {
        String user = "{\"userId\":\"steve\",\"userType\":\"employee\",\"firstName\":\"Steve\",\"lastName\":\"Hu\",\"email\":\"admin@networknt.com\",\"password\":\"123456\",\"passwordConfirm\":\"123456\"}";
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:6885/oauth2/user");
        httpPost.setHeader("Content-type", "application/json");
        httpPost.setEntity(new StringEntity(user));
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            int statusCode = response.getStatusLine().getStatusCode();
            String body = IOUtils.toString(response.getEntity().getContent(), "utf8");
            Assert.assertEquals(400, statusCode);
            if(statusCode == 400) {
                Status status = Config.getInstance().getMapper().readValue(body, Status.class);
                Assert.assertNotNull(status);
                Assert.assertEquals("ERR12021", status.getCode());
                Assert.assertEquals("EMAIL_EXISTS", status.getMessage()); // response_type missing
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Test
    public void testPasswordEmpty() throws ClientException, ApiException, UnsupportedEncodingException {
        String user = "{\"userId\":\"steve\",\"userType\":\"employee\",\"firstName\":\"Steve\",\"lastName\":\"Hu\",\"email\":\"admin1@networknt.com\",\"passwordConfirm\":\"123456\"}";
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:6885/oauth2/user");
        httpPost.setHeader("Content-type", "application/json");
        httpPost.setEntity(new StringEntity(user));
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            int statusCode = response.getStatusLine().getStatusCode();
            String body = IOUtils.toString(response.getEntity().getContent(), "utf8");
            Assert.assertEquals(400, statusCode);
            if(statusCode == 400) {
                Status status = Config.getInstance().getMapper().readValue(body, Status.class);
                Assert.assertNotNull(status);
                Assert.assertEquals("ERR12011", status.getCode());
                Assert.assertEquals("PASSWORD_OR_PASSWORDCONFIRM_EMPTY", status.getMessage()); // response_type missing
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Test
    public void testPasswordAndConfirmNotMatch() throws ClientException, ApiException, UnsupportedEncodingException {
        String user = "{\"userId\":\"steve001\",\"userType\":\"employee\",\"firstName\":\"Steve\",\"lastName\":\"Hu\",\"email\":\"abc@networknt.com\",\"password\":\"123456\",\"passwordConfirm\":\"678901\"}";
        CloseableHttpClient client = Client.getInstance().getSyncClient();
        HttpPost httpPost = new HttpPost("http://localhost:6885/oauth2/user");
        httpPost.setHeader("Content-type", "application/json");
        httpPost.setEntity(new StringEntity(user));
        try {
            CloseableHttpResponse response = client.execute(httpPost);
            int statusCode = response.getStatusLine().getStatusCode();
            String body = IOUtils.toString(response.getEntity().getContent(), "utf8");
            Assert.assertEquals(400, statusCode);
            if(statusCode == 400) {
                Status status = Config.getInstance().getMapper().readValue(body, Status.class);
                Assert.assertNotNull(status);
                Assert.assertEquals("ERR12012", status.getCode());
                Assert.assertEquals("PASSWORD_PASSWORDCONFIRM_NOT_MATCH", status.getMessage()); // response_type missing
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
