  version: '2'
  services:
    oracledb:
      image: wnameless/oracle-xe-11g:16.04
      volumes:
        - ./db/oracle:/docker-entrypoint-initdb.d
      ports:
        - "1521:1521"
      networks:
        - light
    oauth2-code:
      build:
        context: code/
        dockerfile: docker/Dockerfile
      ports:
        - "6881:6881"
      volumes:
        - ./db/oracle/config/oauth2-code:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-code"
      #    env: "dev"
    oauth2-token:
      build:
        context: token/
        dockerfile: docker/Dockerfile
      ports:
        - "6882:6882"
      volumes:
        - ./db/oracle/config/oauth2-token:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-token"
      #    env: "dev"
    oauth2-service:
      build:
        context: service/
        dockerfile: docker/Dockerfile
      ports:
        - "6883:6883"
      volumes:
        - ./db/oracle/config/oauth2-service:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-service"
      #    env: "dev"
    oauth2-client:
      build:
        context: client/
        dockerfile: docker/Dockerfile
      ports:
        - "6884:6884"
      volumes:
        - ./db/oracle/config/oauth2-client:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-client"
      #    env: "dev"
    oauth2-user:
      build:
        context: user/
        dockerfile: docker/Dockerfile
      ports:
        - "6885:6885"
      volumes:
        - ./db/oracle/config/oauth2-user:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-user"
      #    env: "dev"
    oauth2-key:
      build:
        context: key/
        dockerfile: docker/Dockerfile
      ports:
        - "6886:6886"
      volumes:
        - ./db/oracle/config/oauth2-key:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-key"
      #    env: "dev"
    oauth2-refresh-token:
      build:
        context: refresh-token/
        dockerfile: docker/Dockerfile
      ports:
        - "6887:6887"
      volumes:
        - ./db/oracle/config/oauth2-refresh-token:/config
      networks:
        - light
      depends_on:
        - oracledb
      #logging:
      #  driver: "gelf"
      #  options:
      #    gelf-address: "udp://localhost:12201"
      #    tag: "oauth2-refresh-token"
      #    env: "dev"

  networks:
    light:
      driver: bridge
