# This file contains all the secrets for the server and client in order to manage and
# secure all of them in the same place. In Kubernetes, this file will be mapped to
# Secrets and all other config files will be mapped to mapConfig

---

# Sever section

# Key store password, the path of keystore is defined in server.yml
serverKeystorePass: ${secret.serverKeystorePass:password}

# Key password, the key is in keystore
serverKeyPass: ${secret.serverKeyPass:password}

# Trust store password, the path of truststore is defined in server.yml
serverTruststorePass: ${secret.serverTruststorePass:password}


# Client section

# Key store password, the path of keystore is defined in server.yml
clientKeystorePass: ${secret.clientKeystorePass:password}

# Key password, the key is in keystore
clientKeyPass: ${secret.clientKeyPass:password}

# Trust store password, the path of truststore is defined in server.yml
clientTruststorePass: ${secret.clientTruststorePass:password}

# Authorization code client secret for OAuth2 server
clientCredentialsClientSecret: ${secret.clientCredentialsClientSecret:password}

# Client credentials client secret for OAuth2 server
refreshTokenClientSecret: ${secret.refreshTokenClientSecret:password}

# Key distribution client secret for OAuth2 server
keyClientSecret: ${secret.keyClientSecret:password}


# Consul service registry and discovery

# Consul Token for service registry and discovery
# consulToken: the_one_ring

# EmailSender password
emailPassword: ${secret.emailPassword:change-to-real-password}

# jwt private key password, used by light-oauth2 token and code services.
jwtPrivateKeyPassword: ${secret.jwtPrivateKeyPassword:password}
