openapi: 3.0.0
info:
  version: 1.0.0
  title: OAuth2 Client Registration
  description: OAuth2 Client Registration microservices endpoints.
  contact:
    email: stevehu@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
   - url: 'https://oauth2.networknt.com'    
paths:
  /oauth2/client:
    post:
      description: Return a client object
      operationId: createClient
      security:
        - client_auth:
            - oauth.client.w
    put:
      description: Return the updated client
      operationId: updateClient
      security:
        - client_auth:
            - oauth.client.w
    get:
      description: Return all clients
      operationId: getAllClient
      security:
        - client_auth:
            - oauth.client.r
  '/oauth2/client/{clientId}':
    delete:
      description: Delete a client by Id
      operationId: deleteClient
      security:
        - client_auth:
            - oauth.client.w
    get:
      description: Get a client by Id
      operationId: getClient
      security:
        - client_auth:
            - oauth.client.r
            - oauth.client.w
  '/oauth2/client/{clientId}/service':
    delete:
      description: Delete all associated services for a client by clientId
      operationId: deleteAllClientService
      security:
        - client_auth:
            - oauth.client.w
    get:
      description: Get all associated services and endpoints by clientId
      operationId: getAllClientService
      security:
        - client_auth:
            - oauth.client.r
            - oauth.client.w
  '/oauth2/client/{clientId}/service/{serviceId}':
    post:
      description: Link a service and its endpoints to a client
      operationId: linkClientService
      security:
        - client_auth:
            - oauth.client.w
    delete:
      description: Delete all endpoints of a service for a client
      operationId: deleteClientService
      security:
        - client_auth:
            - oauth.client.w
    get:
      description: Get linked endpoints of a service from a client
      operationId: getClientService
      security:
        - client_auth:
            - oauth.client.r
            - oauth.client.w
components:
  securitySchemes:
    client_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://localhost:8888/oauth2/code'
          scopes:
            oauth.client.w: write oauth client
            oauth.client.r: read oauth client