FROM registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

# Add the jar file
ADD target/oauth2-token.jar server.jar

# Port available to the world outside of this container
EXPOSE 8080

CMD ["/bin/sh","-c","java -Dlight-4j-config-dir=/config -Dlogback.configurationFile=/config/logback.xml -jar server.jar"]